/**
 * Extracts the ConditionalTokens creation bytecode from the UMA adapter artifact
 * and writes a Solidity hex constant file at contracts/lib/ConditionalTokensBytecode.sol
 * Run: node scripts/extractCtfBytecode.js
 */
const fs = require('fs');
const path = require('path');

const artifact = require('../lib/uma-ctf-adapter/artifacts/ConditionalTokens.json');
const bytecodeObj = artifact.bytecode;
const bytecode = typeof bytecodeObj === 'string' ? bytecodeObj
  : (bytecodeObj && bytecodeObj.object) ? bytecodeObj.object
  : null;

if (!bytecode) {
  console.error('Could not extract bytecode');
  process.exit(1);
}

const hex = bytecode.startsWith('0x') ? bytecode : '0x' + bytecode;
console.log(`Bytecode length: ${hex.length} chars (${(hex.length - 2) / 2} bytes)`);

const sol = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by scripts/extractCtfBytecode.js — DO NOT EDIT
// ConditionalTokens (Gnosis) v1.0.0 compiled with solc 0.5.1+commit.c8a2cb62
pragma solidity ^0.8.20;

library ConditionalTokensBytecode {
    /// @dev Returns the creation bytecode for the Gnosis ConditionalTokens contract.
    ///      Used in DeployM1.s.sol to deploy CTF without recompiling the 0.5.x source.
    function creationCode() internal pure returns (bytes memory) {
        return hex"${hex.slice(2)}";
    }
}
`;

const outPath = path.join(__dirname, '../contracts/lib/ConditionalTokensBytecode.sol');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, sol);
console.log('Written:', outPath);
